FROM alpine AS build
ENV VERSION=v0.50.18
ARG TARGETARCH

RUN apk add --no-cache wget tar gzip && \
    wget -O /tmp/k9s_Linux_${TARGETARCH}.tar.gz \
    https://github.com/derailed/k9s/releases/download/${VERSION}/k9s_Linux_${TARGETARCH}.tar.gz && \
    tar -xzf /tmp/k9s_Linux_${TARGETARCH}.tar.gz -C /tmp && \
    chmod +x /tmp/k9s

FROM scratch
COPY ./run.sh /
COPY ./run.csx /
COPY --from=build /tmp/k9s ./
