FROM alpine AS build
ENV VERSION=v3.17.2
ARG TARGETARCH

RUN apk add --no-cache wget tar gzip && \
    wget -O /tmp/helm-${VERSION}-linux-${TARGETARCH}.tar.gz \
    https://get.helm.sh/helm-${VERSION}-linux-${TARGETARCH}.tar.gz && \
    tar -xzf /tmp/helm-${VERSION}-linux-${TARGETARCH}.tar.gz -C /tmp && \
    chmod +x /tmp/linux-${TARGETARCH}/helm

FROM scratch
COPY ./run.sh /
COPY ./run.csx /
COPY --from=build /tmp/linux-${TARGETARCH}/helm ./
